version: "2.4"

networks:
  app_network:
    driver: bridge
    name: app_network

services:
  frontend:
    build:
      context: ../frontend
    container_name: frontend
    ports:
      - "3001:3000"
    networks:
      - app_network
    environment:
      - KAFKA_PRODUCER_URL=http://kafka-producer:8000
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    depends_on:
      kafka-producer:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped
    mem_limit: 256m

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      KAFKA_HEAP_OPTS: "-Xmx128m -Xms64m"
      ZOOKEEPER_MAX_CLIENT_CNXNS: 60
      ZOOKEEPER_4LW_COMMANDS_WHITELIST: "*"
    ports:
      - "2181:2181"
    networks:
      - app_network
    restart: unless-stopped
    mem_limit: 256m
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost 2181 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - app_network
    restart: unless-stopped
    mem_limit: 1g
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  kafka-producer:
    build:
      context: ./kafka-producer
    container_name: kafka-producer
    ports:
      - "8000:8000"
    volumes:
      - ../debug-api:/mnt:rw
      - ../:/app:rw
    depends_on:
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      KAFKA_SERVER: "kafka:9092"
      ZOOKEEPER_SERVER: "zookeeper:2181"
      PRODUCER_INTERVAL: 100
    networks:
      - app_network
    restart: unless-stopped
    mem_limit: 256m
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/logs || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  flink-processor:
    build:
      context: ./flink-processor
      dockerfile: Dockerfile
    container_name: flink-processor
    volumes:
      - ../debug-api:/mnt:rw
    depends_on:
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_SERVER: "kafka:9092"
      ZOOKEEPER_SERVER: "zookeeper:2181"
      PRODUCER_INTERVAL: 100
    networks:
      - app_network
    restart: unless-stopped
    mem_limit: 512m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  postgres:
    build:
      context: ./postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5438:5432"
    networks:
      - app_network
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data:rw
    mem_limit: 256m
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  settings:
  data: