version: "3.7"

networks:
  app_network:
    name: application_bridge
    driver: bridge

services:
  frontend:
    build:
      context: ../frontend
    ports:
      - "3001:3000"
    networks:
      - app_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      app_network:
        aliases:
          - zookeeper

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      JMX_PORT: 9999
    networks:
      app_network:
        aliases:
          - kafka

  kafka-producer:
    build:
      context: ./kafka-producer
    volumes:
      - ../debug-api:/mnt
      - ../:/app
    depends_on:
      - kafka
    environment:
      KAFKA_SERVER: "kafka:9092"
      ZOOKEEPER_SERVER: "zookeeper:32181"
      PRODUCER_INTERVAL: 100
    networks:
      - app_network

  flink-processor:
    build:
      context: ./flink-processor
      dockerfile: Dockerfile
    volumes:
      - ../debug-api:/mnt
    depends_on:
      - kafka
    environment:
      KAFKA_SERVER: "kafka:9092"
      ZOOKEEPER_SERVER: "zookeeper:32181"
      PRODUCER_INTERVAL: 100
    networks:
      - app_network

  postgres:
    build:
      context: ./postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5438:5432
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  settings:
  data: