cities:
- London
- Stockholm
- Toronto
- Moscow
- Madrid
- Reykjavik
- Helsinki
- Rome
- Venice
- Lisbon
- Paris
- Amsterdam
- Chernobyl
- Nairobi
- Dubai
- Bali
- Tokyo
- Bangkok
- Seoul
- Buenos Aires
- Mexico City
- Honolulu
- Papeete
- Juneau
- Sacramento
- Tijuana
dynamicCities:
  current:
  - Shanghai
  - Beijing
  - Chengdu
  - Guangzhou
  - Shenzhen
  - Beijing Shi
  - Tianjin
  enabled: true
  previousBatch:
  - Shanghai
  - Beijing
  - Chengdu
  - Guangzhou
  - Shenzhen
  - Beijing Shi
  - Tianjin
services:
  cityApi:
    numberOfCitiesForSelectedCountry: 7
  flinkProcessor:
    batchIntervalMs: 200
    batchSize: 1000
    maxRetries: 5
    sampleDuration: 15
  kafkaProducer:
    requestInterval: 0.01
visualizations:
  charts:
    equatorChart:
      displayActualTrend: false
      displayLinearTrend: true
      displayLogarithmicTrend: true
      pngOutput: false
  queryConfig:
    queryAttribute: continent
    queryRequirement: Europe
