cities:
- London
- Stockholm
- Toronto
- Moscow
- Madrid
- Reykjavik
- Helsinki
- Rome
- Venice
- Lisbon
- Paris
- Amsterdam
- Chernobyl
- Nairobi
- Dubai
- Bali
- Tokyo
- Bangkok
- Seoul
- Buenos Aires
- Mexico City
- Honolulu
- Papeete
- Juneau
- Sacramento
- Tijuana
dynamicCities:
  current:
  - Paris
  - Marseille
  - Lyon
  - Toulouse
  - Nice
  - Nantes
  - Montpellier
  enabled: true
  previousBatch:
  - Paris
  - Marseille
  - Lyon
  - Toulouse
  - Nice
  - Nantes
  - Montpellier
services:
  cityApi:
    numberOfCitiesForSelectedCountry: 7
  flinkProcessor:
    batchIntervalMs: 200
    batchSize: 1000
    maxRetries: 5
    sampleDuration: 15
  kafkaProducer:
    requestInterval: 0.01
visualizations:
  charts:
    equatorChart:
      displayActualTrend: false
      displayLinearTrend: true
      displayLogarithmicTrend: true
      pngOutput: false
  queryConfig:
    queryAttribute: continent
    queryRequirement: Asia
