cities:
- London
- Stockholm
- Toronto
- Moscow
- Madrid
- Reykjavik
- Helsinki
- Rome
- Venice
- Lisbon
- Paris
- Amsterdam
- Chernobyl
- Nairobi
- Dubai
- Bali
- Tokyo
- Bangkok
- Seoul
- Buenos Aires
- Mexico City
- Honolulu
- Papeete
- Juneau
- Sacramento
- Tijuana
- Palermo
- Naples
- Milan
- Budapest
- Bucharest
- Sofia
- Athens
- Warsaw
- Prague
- Zurich
- Geneva
- Rotterdam
- Antwerp
- Brussels
- Cairo
- Addis Ababa
- Dakar
- Abuja
- Luanda
- Kinshasa
- Gaborone
- Pretoria
- Antananarivo
- Abu Dabhi
- Austin
- Boston
- Miami
- San Fransisco
- Seattle
- Denver
- Bogota
- Lima
- Santiago
- Novosibirsk
- Omsk
- Tehran
- Baghdad
- Ankara
- Damascus
- Sao Paulo
- Caracas
- San Jose
- Rio de Janeiro
- Salvador
- Brasilia
- Recife
- Srinagar
- Chennai
- Bangalore
- Ahmedabad
- Ulaanbaatar
- Almaty
- Ganja
- Astana
- Beijing
- Shanghai
- Hong Kong
- Osaka
- Chengdu
dynamicCities:
  current:
  - Stockholm
  - Gothenburg
  - "Malm\xF6"
  - Uppsala
  - "V\xE4ster\xE5s"
  - "\xD6rebro"
  - "Link\xF6ping"
  enabled: true
  previousBatch:
  - Stockholm
  - Gothenburg
  - "Malm\xF6"
  - Uppsala
  - "V\xE4ster\xE5s"
  - "\xD6rebro"
  - "Link\xF6ping"
services:
  cityApi:
    numberOfCitiesForSelectedCountry: 7
  flinkProcessor:
    batchIntervalMs: 200
    batchSize: 1000
    maxRetries: 5
    sampleDuration: 10
  kafkaProducer:
    requestInterval: 0.01
visualizations:
  charts:
    equatorChart:
      displayActualTrend: false
      displayLinearTrend: true
      displayLogarithmicTrend: true
      pngOutput: false
  queryConfig:
    queryAttribute: continent
    queryRequirement: Europe
