cities:
- London
- Stockholm
- Toronto
- Moscow
- Madrid
- Reykjavik
- Helsinki
- Rome
- Venice
- Lisbon
- Paris
- Amsterdam
- Chernobyl
- Nairobi
- Dubai
- Bali
- Tokyo
- Bangkok
- Seoul
- Buenos Aires
- Mexico City
- Honolulu
- Papeete
- Juneau
- Sacramento
- Tijuana
dynamicCities:
  current:
  - Ho Chi Minh City
  - Hanoi
  - "\u0110\u1ED3ng Nai"
  - Haiphong
  - "Ki\xEAn Giang"
  - "C\u1EA7n Th\u01A1"
  - Da Nang
  enabled: true
  previousBatch:
  - Ho Chi Minh City
  - Hanoi
  - "\u0110\u1ED3ng Nai"
  - Haiphong
  - "Ki\xEAn Giang"
  - "C\u1EA7n Th\u01A1"
  - Da Nang
services:
  cityApi:
    numberOfCitiesForSelectedCountry: 7
  flinkProcessor:
    batchIntervalMs: 200
    batchSize: 1000
    maxRetries: 5
    sampleDuration: 15
  kafkaProducer:
    requestInterval: 0.01
visualizations:
  charts:
    equatorChart:
      displayActualTrend: false
      displayLinearTrend: true
      displayLogarithmicTrend: false
      pngOutput: false
  queryConfig:
    queryAttribute: timeZoneOffset
    queryRequirement: UTC+2
