cities:
  - London
  - Stockholm
  - Toronto
  - Moscow
  - Madrid
  - Reykjavik
  - Helsinki
  - Rome
  - Venice
  - Lisbon
  - Paris
  - Amsterdam
  - Chernobyl
  - Nairobi
  - Dubai
  - Bali
  - Tokyo
  - Bangkok
  - Seoul
  - Buenos Aires
  - Mexico City
services:
  kafkaProducer:
    requestInterval: 0.01
  flinkProcessor:
    sampleDuration: 15
    batchSize: 1000
    batchIntervalMs: 200
    maxRetries: 5
visualizations:
  queryConfig:
    queryAttribute: continent
    queryRequirement: Europe
  charts:
    bubbleChart:
      separateGraphDisplay: False
      bubbleColorTheme: brown
      pngOutput: True
    pieChart:
      chartType: Color-Theme
      pieColorTheme: orange
      pngOutput: True
    equatorChart:
      displayLinearTrend: False
      displayLogarithmicTrend: True
      displayActualTrend: False
      pngOutput: False



