cities:
- London
- Stockholm
- Toronto
- Moscow
- Madrid
- Reykjavik
- Helsinki
- Rome
- Venice
- Lisbon
- Paris
- Amsterdam
- Chernobyl
- Nairobi
- Dubai
- Bali
- Tokyo
- Bangkok
- Seoul
- Buenos Aires
- Mexico City
- Honolulu
- Papeete
- Juneau
- Sacramento
- Tijuana
dynamicCities:
  current:
  - Stockholm
  - Gothenburg
  - "Malm\xF6"
  - Uppsala
  - "V\xE4ster\xE5s"
  - "\xD6rebro"
  - "Link\xF6ping"
  enabled: true
  previousBatch:
  - Stockholm
  - Gothenburg
  - "Malm\xF6"
  - Uppsala
  - "V\xE4ster\xE5s"
  - "\xD6rebro"
  - "Link\xF6ping"
services:
  cityApi:
    numberOfCitiesForSelectedCountry: 7
  flinkProcessor:
    batchIntervalMs: 200
    batchSize: 1000
    maxRetries: 5
    sampleDuration: 15
  kafkaProducer:
    requestInterval: 0.01
visualizations:
  charts:
    equatorChart:
      displayActualTrend: false
      displayLinearTrend: true
      displayLogarithmicTrend: false
      pngOutput: false
  queryConfig:
    queryAttribute: timeZoneOffset
    queryRequirement: UTC+1
