cities:
- London
- Stockholm
- Toronto
- Moscow
- Madrid
- Reykjavik
- Helsinki
- Rome
- Venice
- Lisbon
- Paris
- Amsterdam
- Chernobyl
- Nairobi
- Dubai
- Bali
- Tokyo
- Bangkok
- Seoul
- Buenos Aires
- Mexico City
- Honolulu
- Papeete
- Juneau
- Sacramento
- Tijuana
dynamicCities:
  current:
  - Buenos Aires
  - La Matanza Partido
  - "C\xF3rdoba"
  - Rosario
  - La Plata Partido
  - Lomas de Zamora Partido
  - "General Pueyrred\xF3n Partido"
  enabled: true
  previousBatch:
  - Buenos Aires
  - La Matanza Partido
  - "C\xF3rdoba"
  - Rosario
  - La Plata Partido
  - Lomas de Zamora Partido
  - "General Pueyrred\xF3n Partido"
services:
  cityApi:
    numberOfCitiesForSelectedCountry: 7
  flinkProcessor:
    batchIntervalMs: 200
    batchSize: 1000
    maxRetries: 5
    sampleDuration: 15
  kafkaProducer:
    requestInterval: 0.01
visualizations:
  charts:
    equatorChart:
      displayActualTrend: false
      displayLinearTrend: false
      displayLogarithmicTrend: true
      pngOutput: false
  queryConfig:
    queryAttribute: timeZoneOffset
    queryRequirement: UTC+0
