apiVersion: apps/v1
kind: Deployment
metadata:
  name: city-api
  namespace: global-city-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: city-api
  template:
    metadata:
      labels:
        app: city-api
    spec:
      serviceAccountName: city-api-sa
      initContainers:
      - name: init-dirs
        image: busybox
        command: ['/bin/sh', '-c']
        args:
        - |
          # Create base directories
          mkdir -p /target/city_api
          mkdir -p /target/shared/weather
          
          # Debug: List available files
          echo "Available files in /config-files:"
          ls -la /config-files
          
          # Copy and rename files for city-api package
          cp /config-files/city-api.init.py /target/city_api/__init__.py
          cp /config-files/city-api.main.py /target/city_api/main.py
          
          # Copy config files
          mkdir -p /target/city_api/config
          cp /config-files/city-api.config.configuration.yml /target/city_api/config/configuration.yml
          cp /config-files/city-api.config.city-edits.yml /target/city_api/config/city-edits.yml
          cp /config-files/city-api.config.country-codes.json /target/city_api/config/country-codes.json
          cp /config-files/city-api.countryCities.sh /target/city_api/countryCities.sh
          
          # Copy shared module files
          cp /config-files/shared.init.py /target/shared/__init__.py
          cp /config-files/shared.utils.py /target/shared/utils.py
          cp /config-files/shared.weather.init.py /target/shared/weather/__init__.py
          cp /config-files/shared.weather.api.py /target/shared/weather/api.py
          cp /config-files/shared.weather.city_coordinates.py /target/shared/weather/city_coordinates.py
          
          # Debug: List target directories
          echo "Contents of /target/city_api:"
          ls -la /target/city_api
          echo "Contents of /target/city_api/config:"
          ls -la /target/city_api/config
          echo "Contents of /target/shared/weather:"
          ls -la /target/shared/weather
          
          # Set permissions
          find /target -type d -exec chmod 755 {} \;
          find /target -type f -exec chmod 644 {} \;
          chmod +x /target/city_api/countryCities.sh || echo "Warning: Could not chmod countryCities.sh"
          chmod +x /target/shared/weather/city_coordinates.py || echo "Warning: Could not chmod city_coordinates.py"
        volumeMounts:
        - name: app-files
          mountPath: /config-files
        - name: config-dir
          mountPath: /target
      containers:
      - name: city-api
        image: joel030303/city-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8003
        command: ["python", "-m", "uvicorn"]
        args: ["city_api.main:app", "--host", "0.0.0.0", "--port", "8003"]
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        env:
        - name: PYTHONPATH
          value: /app
        - name: PORT
          value: "8003"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka-0.kafka.global-city-streaming.svc.cluster.local:9092
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: WEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: weather-api-key
        - name: GEODB_CITIES_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: geodb-cities-api-key
        volumeMounts:
        - name: config-dir
          mountPath: /app
        - name: app-config
          mountPath: /app/configuration.yml
          subPath: configuration.yml
      volumes:
      - name: app-files
        configMap:
          name: app-files
          defaultMode: 0755
      - name: config-dir
        emptyDir: {}
      - name: app-config
        configMap:
          name: app-config-yml
