apiVersion: apps/v1
kind: Deployment
metadata:
  name: city-api
  namespace: global-city-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: city-api
  template:
    metadata:
      labels:
        app: city-api
    spec:
      containers:
      - name: city-api
        image: city-api:latest
        imagePullPolicy: Never
        command: ["uvicorn"]
        args: ["main:app", "--host", "0.0.0.0", "--port", "8000"]
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        env:
        - name: PYTHONPATH
          value: "/app"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-0.kafka.global-city-streaming.svc.cluster.local:9092"
        volumeMounts:
        - name: app-code
          mountPath: /app
      volumes:
      - name: app-code
        configMap:
          name: city-api-code
