apiVersion: v1
kind: Service
metadata:
  name: city-api
  namespace: global-city-streaming
spec:
  selector:
    app: city-api
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: LoadBalancer 