apiVersion: v1
kind: Service
metadata:
  name: city-api
  namespace: global-city-streaming
spec:
  ports:
  - port: 8003
    targetPort: 8003
    name: http
  selector:
    app: city-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: city-api
  namespace: global-city-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: city-api
  template:
    metadata:
      labels:
        app: city-api
    spec:
      containers:
      - name: city-api
        image: joel030303/city-api:latest
        ports:
        - containerPort: 8003
        env:
        - name: PYTHONPATH
          value: "/app/city-api"
        - name: GEODB_CITIES_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: geodb-cities-api-key
        - name: WEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: weather-api-key
        - name: GIPHY_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: giphy-api-key
        volumeMounts:
        - name: config-volume
          mountPath: /app/configuration.yml
          subPath: configuration.yml
          readOnly: true
        - name: generated-artifacts
          mountPath: /app/city-api/generated-artifacts
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /ready
            port: 8003
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /ready
            port: 8003
          initialDelaySeconds: 15
          periodSeconds: 10
      volumes:
      - name: config-volume
        configMap:
          name: app-config-yml
      - name: generated-artifacts
        emptyDir: {}
