apiVersion: apps/v1
kind: Deployment
metadata:
  name: city-api
  namespace: global-city-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: city-api
  template:
    metadata:
      labels:
        app: city-api
    spec:
      serviceAccountName: city-api-sa
      initContainers:
      - name: init-config
        image: busybox
        command: ['/bin/sh', '-c']
        args:
        - |
          # Create target directories
          mkdir -p /target/city_api/config
          mkdir -p /target/shared/weather
          
          # Copy files from ConfigMap
          cp -L /app-code/* /target/city_api/ || true
          
          # Copy files from shared-files
          cp -L /shared-files/country-codes.json /target/city_api/config/
          cp -L /shared-files/countryCities.sh /target/city_api/
          cp -L /shared-files/utils.py /target/shared/
          cp -L /shared-files/weather.api.py /target/shared/weather/api.py
          cp -L /shared-files/weather.city_coordinates.py /target/shared/weather/city_coordinates.py
          cp -L /shared-files/weather.__init__.py /target/shared/weather/__init__.py
          cp -L /shared-files/__init__.py /target/shared/
          
          # Create __init__.py files if they don't exist
          touch /target/shared/__init__.py
          touch /target/shared/weather/__init__.py
          
          # Ensure files are executable
          chmod +x /target/city_api/countryCities.sh
          chmod +x /target/shared/weather/city_coordinates.py
          
          # List contents for debugging
          echo "Contents of /target/city_api:"
          ls -la /target/city_api/
          echo "Contents of /target/shared/weather:"
          ls -la /target/shared/weather/
          
          # Ensure files are readable
          chmod -R 644 /target/shared/weather/*
          chmod -R 644 /target/city_api/*
          find /target -type d -exec chmod 755 {} \;
          chmod +x /target/city_api/countryCities.sh
          chmod +x /target/shared/weather/city_coordinates.py
        volumeMounts:
        - name: shared-files
          mountPath: /shared-files
        - name: app-code
          mountPath: /app-code
        - name: config-dir
          mountPath: /target
      containers:
      - name: city-api
        image: joel030303/city-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8003
        command: ["python", "-m", "uvicorn"]
        args: ["city_api.main:app", "--host", "0.0.0.0", "--port", "8003"]
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        env:
        - name: PYTHONPATH
          value: /app
        - name: PORT
          value: "8003"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka-0.kafka.global-city-streaming.svc.cluster.local:9092
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: WEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: weather-api-key
        - name: GEODB_CITIES_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: geodb-cities-api-key
        volumeMounts:
        - name: config-dir
          mountPath: /app
        - name: app-config
          mountPath: /app/configuration.yml
          subPath: configuration.yml
      volumes:
      - name: app-code
        configMap:
          name: city-api-code
      - name: app-config
        configMap:
          name: app-config-yml
      - name: shared-files
        configMap:
          name: shared-files
          defaultMode: 0755
      - name: config-dir
        emptyDir: {}
