apiVersion: apps/v1
kind: Deployment
metadata:
  name: city-api
  namespace: global-city-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: city-api
  template:
    metadata:
      labels:
        app: city-api
    spec:
      serviceAccountName: city-api-sa
      containers:
      - name: city-api
        image: joel030303/city-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8003
        command: ["python", "-m", "uvicorn"]
        args: ["city_api.main:app", "--host", "0.0.0.0", "--port", "8003"]
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        env:
        - name: PYTHONPATH
          value: /app
        - name: PORT
          value: "8003"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka-0.kafka.global-city-streaming.svc.cluster.local:9092
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: WEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: weather-api-key
        - name: GEODB_CITIES_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: geodb-cities-api-key
        volumeMounts:
        # Mount city-api files
        - name: app-files
          mountPath: /app/city-api/config/configuration.yml
          subPath: city-api/config/configuration.yml
        - name: app-files
          mountPath: /app/city-api/config/city-edits.yml
          subPath: city-api/config/city-edits.yml
        - name: app-files
          mountPath: /app/city-api/config/country-codes.json
          subPath: city-api/config/country-codes.json
        - name: app-files
          mountPath: /app/city-api/countryCities.sh
          subPath: city-api/countryCities.sh
        # Mount shared files
        - name: app-files
          mountPath: /app/shared/__init__.py
          subPath: shared/__init__.py
        - name: app-files
          mountPath: /app/shared/utils.py
          subPath: shared/utils.py
        - name: app-files
          mountPath: /app/shared/weather/__init__.py
          subPath: shared/weather/__init__.py
        - name: app-files
          mountPath: /app/shared/weather/api.py
          subPath: shared/weather/api.py
        - name: app-files
          mountPath: /app/shared/weather/city_coordinates.py
          subPath: shared/weather/city_coordinates.py
        # Mount configuration
        - name: app-config
          mountPath: /app/configuration.yml
          subPath: configuration.yml
      volumes:
      - name: app-files
        configMap:
          name: app-files
          defaultMode: 0755
      - name: app-config
        configMap:
          name: app-config-yml
