apiVersion: apps/v1
kind: Deployment
metadata:
  name: city-api
  namespace: global-city-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: city-api
  template:
    metadata:
      labels:
        app: city-api
    spec:
      serviceAccountName: city-api-sa
      initContainers:
      - name: init-dirs
        image: busybox
        command: ['/bin/sh', '-c']
        args:
        - |
          # Create base directories
          mkdir -p /app/city_api
          mkdir -p /app/shared/weather
          
          # Debug: List available files
          echo "Starting initialization..."
          echo "Created directories. Listing source files:"
          echo "Contents of /shared:"
          ls -la /shared
          echo "Contents of /city-api:"
          ls -la /city-api
          
          # Copy shared module files
          echo "Setting up shared module..."
          cp /shared/__init__.py /app/shared/
          cp /shared/utils.py /app/shared/
          cp /shared/weather.__init__.py /app/shared/weather/__init__.py
          cp /shared/weather.api.py /app/shared/weather/api.py
          cp /shared/weather.city_coordinates.py /app/shared/weather/city_coordinates.py
          
          # Copy city-api files
          echo "Setting up city-api module..."
          cp /city-api/__init__.py /app/city_api/
          cp /city-api/main.py /app/city_api/
          mkdir -p /app/city_api/config
          cp /city-api/config.* /app/city_api/config/
          
          # Set permissions
          echo "Setting permissions..."
          find /app -type d -exec chmod 755 {} \;
          find /app -type f -exec chmod 644 {} \;
          
          # Debug: Show final structure
          echo "Final directory structure:"
          find /app -type d -exec sh -c 'echo; echo "{}:"; ls -la "{}"' \;
        volumeMounts:
        - name: shared-files
          mountPath: /shared
        - name: city-api-files
          mountPath: /city-api
        - name: config-dir
          mountPath: /app
      containers:
      - name: city-api
        image: joel030303/city-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8003
        command: ["python", "-m", "uvicorn"]
        args: ["city_api.main:app", "--host", "0.0.0.0", "--port", "8003"]
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        env:
        - name: PYTHONPATH
          value: /app
        - name: PORT
          value: "8003"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka-0.kafka.global-city-streaming.svc.cluster.local:9092
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: WEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: weather-api-key
        - name: GEODB_CITIES_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: geodb-cities-api-key
        volumeMounts:
        - name: config-dir
          mountPath: /app
        - name: app-config
          mountPath: /app/configuration.yml
          subPath: configuration.yml
      volumes:
      - name: shared-files
        configMap:
          name: shared-files
      - name: city-api-files
        configMap:
          name: city-api-files
      - name: config-dir
        emptyDir: {}
      - name: app-config
        configMap:
          name: app-config-yml
