apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-manager
  namespace: global-city-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-manager
  template:
    metadata:
      labels:
        app: db-manager
    spec:
      containers:
      - name: db-manager
        image: joel030303/db-manager:latest
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2560Mi
        env:
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "postgres"
        - name: MAX_RECORDS
          value: "2000"
        - name: CHECK_INTERVAL
          value: "60"
        - name: BATCH_DELETE_SIZE
          value: "10000"
