apiVersion: v1
kind: Service
metadata:
  name: flink-processor
  namespace: global-city-streaming
spec:
  ports:
  - port: 8001
    targetPort: 8001
    name: http
  selector:
    app: flink-processor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-processor
  namespace: global-city-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-processor
  template:
    metadata:
      labels:
        app: flink-processor
    spec:
      containers:
      - name: flink-processor
        image: joel030303/flink-processor:latest
        ports:
        - containerPort: 8001
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        env:
        - name: KAFKA_SERVER
          value: "kafka-0.kafka.global-city-streaming.svc.cluster.local:9092"
        - name: ZOOKEEPER_SERVER
          value: "zookeeper-0.zookeeper.global-city-streaming.svc.cluster.local:2181"
        - name: PRODUCER_INTERVAL
          value: "100"
        - name: FLINK_ENV_JAVA_OPTS
          value: "-XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:+AggressiveOpts"
        - name: FLINK_ENV_JAVA_OPTS_JM
          value: "-Xmx1g -Xms1g"
        - name: FLINK_ENV_JAVA_OPTS_TM
          value: "-Xmx1g -Xms1g"
        - name: FLINK_MAX_PARALLELISM
          value: "8"
        - name: FLINK_PARALLELISM
          value: "4"
