apiVersion: v1
kind: Service
metadata:
  name: flink-processor
  namespace: global-city-streaming
spec:
  ports:
  - port: 8001
    targetPort: 8001
    name: http
  selector:
    app: flink-processor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-processor
  namespace: global-city-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-processor
  template:
    metadata:
      labels:
        app: flink-processor
    spec:
      containers:
      - name: flink-processor
        image: joel030303/flink-processor:latest
        ports:
        - containerPort: 8001
        env:
        - name: KAFKA_SERVER
          value: "kafka:9092"
        - name: ZOOKEEPER_SERVER
          value: "zookeeper:2181"
        - name: FLINK_ENV_JAVA_OPTS
          value: "-XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:+AggressiveOpts"
        - name: FLINK_MAX_PARALLELISM
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FLINK_MAX_PARALLELISM
        - name: FLINK_PARALLELISM
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FLINK_PARALLELISM
        resources:
          limits:
            memory: "5Gi"
            cpu: "2000m"
          requests:
            memory: "2Gi"
            cpu: "1000m"
