apiVersion: v1
kind: Service
metadata:
  name: kafka-producer
  namespace: global-city-streaming
spec:
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  selector:
    app: kafka-producer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: global-city-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      initContainers:
      - name: copy-files
        image: busybox
        command: ['sh', '-c', 'mkdir -p /app/shared/weather && cp /source/__init__.py /source/utils.py /app/shared/ && cp /source/weather.__init__.py /app/shared/weather/__init__.py && cp /source/weather.api.py /app/shared/weather/api.py && mkdir -p /app/shared/monitoring && cp /source/monitoring.exec-settings.txt /app/shared/monitoring/exec-settings.txt']
        volumeMounts:
        - name: shared-source
          mountPath: /source
        - name: shared-volume
          mountPath: /app/shared
      containers:
      - name: kafka-producer
        image: joel030303/kafka-producer:latest
        ports:
        - containerPort: 8000
        env:
        - name: KAFKA_SERVER
          value: "kafka-0.kafka.global-city-streaming.svc.cluster.local:9092"
        - name: ZOOKEEPER_SERVER
          value: "zookeeper-0.zookeeper.global-city-streaming.svc.cluster.local:2181"
        - name: PRODUCER_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PRODUCER_INTERVAL
        - name: WEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: weather-api-key
        - name: PYTHONPATH
          value: "/app:/app/shared"
        volumeMounts:
        - name: config-volume
          mountPath: /app/configuration.yml
          subPath: configuration.yml
          readOnly: true
        - name: shared-volume
          mountPath: /app/shared
        resources:
          limits:
            cpu: "2"
            memory: "5Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
      volumes:
      - name: config-volume
        configMap:
          name: app-config-yml
      - name: shared-volume
        emptyDir: {}
      - name: shared-source
        configMap:
          name: shared-files
