apiVersion: v1
kind: Service
metadata:
  name: kafka-producer
  namespace: global-city-streaming
spec:
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  selector:
    app: kafka-producer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: global-city-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: kafka-producer
        image: joel030303/kafka-producer:latest
        ports:
        - containerPort: 8000
        env:
        - name: KAFKA_SERVER
          value: "kafka-0.kafka.global-city-streaming.svc.cluster.local:9092"
        - name: ZOOKEEPER_SERVER
          value: "zookeeper-0.zookeeper.global-city-streaming.svc.cluster.local:2181"
        - name: PRODUCER_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PRODUCER_INTERVAL
        - name: WEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: weather-api-key
        - name: PYTHONPATH
          value: "/app"
        volumeMounts:
        - name: config-volume
          mountPath: /app/configuration.yml
          subPath: configuration.yml
          readOnly: true
        resources:
          limits:
            memory: "5Gi"
            cpu: "2000m"
          requests:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: config-volume
        configMap:
          name: app-config-yml
