apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: global-city-streaming
spec:
  ports:
  - port: 2181
    name: client
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  selector:
    app: zookeeper
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: global-city-streaming
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: volume-permissions
        image: busybox
        securityContext:
          runAsUser: 0
        command:
        - sh
        - -c
        - |
          echo "Setting up Zookeeper permissions..."
          chown -R 1000:1000 /var/lib/zookeeper/data
        volumeMounts:
        - name: data
          mountPath: /var/lib/zookeeper/data
      - name: init-config
        image: busybox
        command:
        - sh
        - -c
        - |
          echo "Creating JAAS config for Zookeeper..."
          mkdir -p /etc/kafka/secrets
          cat > /etc/kafka/secrets/zookeeper_jaas.conf << EOF
          Server {
              org.apache.zookeeper.server.auth.DigestLoginModule required
              user_admin="admin-secret";
          };
          EOF
          chmod 644 /etc/kafka/secrets/zookeeper_jaas.conf
        volumeMounts:
        - name: secrets
          mountPath: /etc/kafka/secrets
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.3.2
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_INIT_LIMIT
          value: "5"
        - name: ZOOKEEPER_SYNC_LIMIT
          value: "2"
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx512m -Xms256m"
        - name: ZOOKEEPER_MAX_CLIENT_CNXNS
          value: "60"
        - name: ZOOKEEPER_4LW_COMMANDS_WHITELIST
          value: "*"
        - name: ZOOKEEPER_SERVER_ID
          value: "1"
        - name: ZOOKEEPER_SERVERS
          value: "zookeeper-0.zookeeper.global-city-streaming.svc.cluster.local:2888:3888"
        - name: KAFKA_OPTS
          value: "-Djava.security.auth.login.config=/etc/kafka/secrets/zookeeper_jaas.conf -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider"
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 768Mi
        volumeMounts:
        - name: data
          mountPath: /var/lib/zookeeper/data
        - name: secrets
          mountPath: /etc/kafka/secrets
      volumes:
      - name: secrets
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: kafka-zk-storage
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: global-city-streaming
spec:
  ports:
  - port: 9092
    name: kafka
  selector:
    app: kafka
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: global-city-streaming
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        fsGroup: 1001
      initContainers:
      - name: volume-permissions
        image: busybox
        securityContext:
          runAsUser: 0
        command:
        - sh
        - -c
        - |
          echo "Setting up Kafka permissions..."
          chown -R 1001:1001 /bitnami/kafka
        volumeMounts:
        - name: data
          mountPath: /bitnami/kafka
      - name: init-config
        image: busybox
        command:
        - sh
        - -c
        - |
          echo "Creating JAAS config for Kafka..."
          mkdir -p /etc/kafka/secrets
          cat > /etc/kafka/secrets/kafka_jaas.conf << EOF
          Client {
              org.apache.zookeeper.server.auth.DigestLoginModule required
              username="admin"
              password="admin-secret";
          };
          EOF
          chmod 644 /etc/kafka/secrets/kafka_jaas.conf
        volumeMounts:
        - name: secrets
          mountPath: /etc/kafka/secrets
      containers:
      - name: kafka
        image: bitnami/kafka:3.5
        ports:
        - containerPort: 9092
        env:
        - name: BITNAMI_DEBUG
          value: "true"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_ENABLE_KRAFT
          value: "no"
        - name: KAFKA_CFG_BROKER_ID
          value: "1"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: "zookeeper-0.zookeeper.global-city-streaming.svc.cluster.local:2181"
        - name: KAFKA_CFG_LISTENERS
          value: "PLAINTEXT://:9092"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-0.kafka.global-city-streaming.svc.cluster.local:9092"
        - name: KAFKA_CFG_NUM_PARTITIONS
          value: "3"
        - name: KAFKA_CFG_DEFAULT_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx512m -Xms256m"
        - name: KAFKA_OPTS
          value: "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_jaas.conf"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 1Gi
        volumeMounts:
        - name: data
          mountPath: /bitnami/kafka
        - name: secrets
          mountPath: /etc/kafka/secrets
      volumes:
      - name: secrets
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: kafka-zk-storage
      resources:
        requests:
          storage: 10Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kafka-zk-storage
provisioner: dobs.csi.digitalocean.com
parameters:
  type: gp3
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete 