apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: city-streaming
spec:
  ports:
  - port: 5432
    name: postgres
  selector:
    app: postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: city-streaming
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: joel030303/postgres:latest  # You should specify your custom postgres image here
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_SHARED_BUFFERS
          value: "1GB"
        - name: POSTGRES_WORK_MEM
          value: "16MB"
        - name: POSTGRES_MAINTENANCE_WORK_MEM
          value: "256MB"
        - name: POSTGRES_EFFECTIVE_CACHE_SIZE
          value: "3GB"
        resources:
          limits:
            memory: "5Gi"
            cpu: "2000m"
          requests:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: city-streaming
type: Opaque
data:
  username: cG9zdGdyZXM=  # base64 encoded 'postgres'
  password: cG9zdGdyZXM=  # base64 encoded 'postgres' 