apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-code
  namespace: {{ .Release.Namespace }}
data:
  {{- (.Files.Glob "../../shared/**/*").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: city-api-code
  namespace: {{ .Release.Namespace }}
data:
  {{- (.Files.Glob "../../city-api/**/*").AsConfig | nindent 2 }} 