apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-code
  namespace: {{ .Release.Namespace }}
data:
  "__init__.py": {{ (.Files.Get "files/shared/__init__.py") | quote }}
  "utils.py": {{ (.Files.Get "files/shared/utils.py") | quote }}
  "weather.__init__.py": {{ (.Files.Get "files/shared/weather/__init__.py") | quote }}
  "weather.api.py": {{ (.Files.Get "files/shared/weather/api.py") | quote }}
  "weather.city_coordinates.py": {{ (.Files.Get "files/shared/weather/city_coordinates.py") | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: city-api-code
  namespace: {{ .Release.Namespace }}
data:
  "__init__.py": {{ (.Files.Get "files/city-api/__init__.py") | quote }}
  "main.py": {{ (.Files.Get "files/city-api/main.py") | quote }}
  "config.configuration.yml": {{ (.Files.Get "files/city-api/config/configuration.yml") | quote }}
  "config.city-edits.yml": {{ (.Files.Get "files/city-api/config/city-edits.yml") | quote }}
  "config.country-codes.json": {{ (.Files.Get "files/city-api/config/country-codes.json") | quote }} 