apiVersion: v1
kind: ServiceAccount
metadata:
  name: city-api-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-logs-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: city-api-logs-reader
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: city-api-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: pod-logs-reader
  apiGroup: rbac.authorization.k8s.io 